### PR TITLE
feat: add React support and use react context

### PR DESCRIPTION
**Pull request by Paul-Isache**

### CODE REVIEW

**Comment by simoneb** [comment]
@galvez are you planning to merge this PR or is it missing something you think it should contain to go in?

**Comment by galvez** [comment]
@simoneb will merge, document and do final cleanups before release tomorrow.

**Comment by galvez** [comment]
Had an [atypically busy](https://twitter.com/anothergalvez/status/1378664722250235904) week ;)

**Comment by simoneb** [comment]
> Had an [atypically busy](https://twitter.com/anothergalvez/status/1378664722250235904) week ;)

Thank you and I'm sorry to hear that your going through this, even though I'm really glad that everything's going alright. Best of luck to both of you!

**Review by galvez — APPROVED** [review]
LGTM, thank you once again @Paul-Isache and @simoneb -- I'm doing pre-release tweaks and fixes directly in the `dev` branch and will let you know when it's out!

**Pull request merged**
